name: Build

on: [push]

jobs:
  build_android:
    runs-on: ubuntu-20.04

    env:
      ANDROID_NDK: android-ndk-r17b
      ANDROID_NDK_HOME: $HOME/$ANDROID_NDK

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node.js
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-modules-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
            distribution: 'jetbrains'
            java-version: '2022.1'

      - name: Setup Android SDK (API Level 19)
        uses: android-actions/setup-android@v2
        with:
          api-level: 19
          ndk: true
          build-tools: 25.2.5

      - name: Download NDK
        run: |
          curl -o $ANDROID_NDK-linux-x86_64.zip https://dl.google.com/android/repository/$ANDROID_NDK-linux-x86_64
          unzip $ANDROID_NDK-linux-x86_64 -d $ANDROID_NDK_HOME
          rm $ANDROID_NDK-linux-x86_64

      - name: Set NDK path
        run: |
          echo "ndk.dir=$ANDROID_NDK_HOME" > $GITHUB_WORKSPACE/local.properties

      - name: Verify NDK installation
        run: |
          echo "NDK_HOME=$NDK_HOME"
          ls -la $NDK_HOME

      - name: Install Dependencies
        run: npm install
        working-directory: telon-gateway-app

      - name: Build Android App Bundle
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release
        working-directory: telon-gateway-app

      - name: Build Android Release
        run: |
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}
        working-directory: telon-gateway-app/android

  download_bundle:
    runs-on: ubuntu-20.04

    needs: build_android

    steps:
      - name: Download Android App Bundle
        run: |
          mkdir -p $GITHUB_WORKSPACE/dist
          cp $GITHUB_WORKSPACE/android/app/build/outputs/bundle/release/app-release.aab $GITHUB_WORKSPACE/dist
        working-directory: telon-gateway-app

      - name: Archive Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: $GITHUB_WORKSPACE/dist
